apiVersion: v2
name: retrotro-helm
description: RetroTro - Agile retrospective tool
type: application
version: 0.0.3
appVersion: 0.0.3
keywords:
  - retrospective
  - agile
  - scrum
  - team
home: https://github.com/jycamier/retrotro
sources:
  - https://github.com/jycamier/retrotro
maintainers:
  - name: jycamier
dependencies:
  - name: postgresql
    version: 13.2.24
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
