apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "retrotro.fullname" . }}-frontend-caddyfile
  labels:
    {{- include "retrotro.frontend.labels" . | nindent 4 }}
data:
  Caddyfile: |
{{- .Values.frontend.caddyfile | nindent 4 }}
