apiVersion: v1
kind: Secret
metadata:
  name: {{ include "retrotro.fullname" . }}-secrets
  labels:
    {{- include "retrotro.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ include "retrotro.databaseUrl" . | quote }}
  {{- if .Values.jwt.secret }}
  jwt-secret: {{ .Values.jwt.secret | quote }}
  {{- else }}
  jwt-secret: {{ randAlphaNum 64 | quote }}
  {{- end }}
  {{- if .Values.oidc.clientSecret }}
  oidc-client-secret: {{ .Values.oidc.clientSecret | quote }}
  {{- end }}
